Enable MacOS Catalyst support
pwa-builder/pwabuilder-ios pull request #14
Opened 2021-10-30 09:01 UTC by khmyznikov

MacOS fixes: window header calculation, app icon.
Storyboard: remove redundant backgrounds, fix icon/progress bar alignment.

2021-11-05 09:18 UTC, khmyznikov commented
Added missing permissions according to issue #18
Navigation gestures allowed according to issue #20

2021-11-09 00:39 UTC, JudahGabriel commented
Gleb, you are amazing.

Just got back from a quick vacation week and you've already implemented some great things.

Question:

You added camera, location, and microphone permissions. Will the user need to allocate those permissions when [creating their Bundle ID](https://github.com/pwa-builder/pwabuilder-ios/blob/main/submit-to-app-store.md#2-create-your-bundle-id)? If so, we'll need to update our docs to include those.

2021-11-09 08:19 UTC, khmyznikov commented
> Just got back from a quick vacation week and you've already implemented some great things.

Glad to try!

> You added camera, location, and microphone permissions. Will the user need to allocate those permissions when [creating their Bundle ID](https://github.com/pwa-builder/pwabuilder-ios/blob/main/submit-to-app-store.md#2-create-your-bundle-id)? If so, we'll need to update our docs to include those.

I don't think so, looks like it doesn't count as [capabilities](https://developer.apple.com/documentation/xcode/adding-capabilities-to-your-app). It works like a passthrough from WebView to prevent unexpected requests, and technically I have added Descriptions, not Permissions.

2021-11-09 17:03 UTC, khmyznikov commented
Display web view full-screen issue #17

2021-11-09 19:30 UTC, JudahGabriel commented
Thanks. I added a question in the code review, see above.

2021-11-10 19:32 UTC, JudahGabriel requested changes

2021-11-10 20:18 UTC, khmyznikov commented on Microsoft.PWABuilder.IOS.Web/Resources/ios-project-src/pwa-shell/Base.lproj/Main.storyboard
> +                                <color key="backgroundColor" red="0.22232502700000001" green="0.4557446241" blue="0.7985594869" alpha="1" colorSpace="custom" customColorSpace="displayP3"/>
Nothing special, maybe this color was too bright for me and I’m muted it. You can override it back as you need.

2021-11-11 00:56 UTC, JudahGabriel approved these changes

2021-11-11 00:56 UTC, JudahGabriel commented
Thanks Gleb! I've merged this in. I'll test it with the generation service, and if all looks good, publish to prod.

2021-11-11 00:56 UTC, merged

2021-11-29 23:23 UTC, JudahGabriel commented
Hey @khmyznikov 

Testing your changes out in the template, I see this:

![image](https://user-images.githubusercontent.com/312936/143958329-ec1edfdd-de99-494c-a888-83cc6013deb4.png)

Clearly not what we're intending here. Want me to fix it? I just don't want to lose any other changes you did.

2021-11-29 23:26 UTC, JudahGabriel commented
In essence, your PR changes the Loading View to be a square in the center of the screen:

![image](https://user-images.githubusercontent.com/312936/143958529-74b96ddb-4062-4073-a5be-c8d40ce4f520.png)

PWABuilder is currently using Loading View as the splash screen, however. 

So, we have 2 ways of fixing this:

- Make Loading View take up all the space
- Add another element behind Loading View, e.g. Splash View, that takes up all the space and acts as the splash screen background.

Thoughts?

2021-12-09 18:30 UTC, khmyznikov commented
@JudahGabriel I think we already discussed something related to this. Looks like it's because I have deleted some of the background colors you inserted. If I remember right, the loading view doesn't need to be stretched to full screen, just paint another View to the same color. I can try to look at it in a few days if you don't find a solution earlier.

2021-12-09 18:36 UTC, JudahGabriel commented
Understood. I'll update the code accordingly, leaving the loading view unstretched. Thanks!

2021-12-28 23:44 UTC, JudahGabriel commented
Hey Gleb. Yeah, I added a new UIView to Main.storyboard that acts as the background splash color. See https://github.com/pwa-builder/pwabuilder-ios/commit/95685e3ef393f9f1af640464f42a1faa3d853e05#diff-33199783740aa45ff5fbc93443437e903caa7eef0fffd6802829bbbacf9b9580L24-L53

I also updated ViewController.swift to set the top frame of the new UIView to be just underneath the status bar. See https://github.com/pwa-builder/pwabuilder-ios/commit/95685e3ef393f9f1af640464f42a1faa3d853e05#diff-6b2e29fc0cadcddfe086b0a4606f20d23891dde4ca6267a500b3cdef4f484157R85-R88

Publishing this to production today, finally. :-)